name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: configure (debug)
      run: ./configure debug
    - name: make (debug)
      run: make
    - name: configure (release)
      run: ./configure release
    - name: make (release)
      run: make
